site_name: REGO
site_description: TEST TEST TEST
repo_name: drorivry/rego
repo_url: https://github.com/drorivry/rego
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true
- attr_list
- md_in_html
extra:
  analytics:
    provider: google
    property: G-YNEVN69SC3
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/tiangolo/fastapi
  - icon: fontawesome/brands/discord
    link: https://discord.gg/VQjSZaeJmf
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/fastapi
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/tiangolo
  - icon: fontawesome/brands/dev
    link: https://dev.to/tiangolo
  - icon: fontawesome/brands/medium
    link: https://medium.com/@tiangolo
  - icon: fontawesome/solid/globe
    link: https://tiangolo.com
edit_uri: ''
plugins:
- search
- markdownextradata:
    data: data
theme:
  name: material
  logo: rego.png
  favicon: rego.png
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: cyan
      accent: deep orange