apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: rego-manager
rules:
- apiGroups: ["*"]
  resources: ["jobs", "pods", "configmaps", "secrets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: role-rego
 namespace: default
subjects:
- kind: ServiceAccount
  name: rego-account
  namespace: default
roleRef:
 kind: Role
 name: rego-manager
 apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: rego-account
  namespace: default